require(tidyverse)
require(magrittr)
require(rstan)
require(bridgesampling)
require(loo)
require(kableExtra)
require(xlsx)

#' Generate data frame from input spreadsheet
#'
#' @param fn Name of spreadsheet file containing data
#' @param use_strain Boolean variable indicating whether the strain column should also be used for subtyping
#'
#' @return Data frame containing data extracted from spreadsheet
#' @export
#'
#' @examples
process_input_xlsx <- function(fn = "progression_estimation_input.xlsx", use_strain = FALSE) {
  max_col_num <- 7
  if (use_strain) {
    max_col_num <- 8
  }
  input_df <-
    xlsx::read.xlsx(
      file = fn,
      sheetIndex = 1,
      colIndex = 1:max_col_num,
      header = TRUE
    ) %>%
    dplyr::mutate(study = factor(study)) %>%
    dplyr::mutate(categorisation = factor(categorisation))
  return(input_df)
}

#' Generate model input from input data frame
#'
#' @param input_df Data frame containing details of case-carrier studies
#' @param subtype Name of column in input data frame used for subtyping information
#'
#' @return A list of lists used as an input to stan models
#' @export
#'
#' @examples
#' process_input_data(S_pneumoniae_infant_serotype, subtype = "categorisation")
process_input_data <- function(input_df, subtype = "categorisation") {
  i_values <- as.integer(input_df$study)
  j_values <- as.integer(input_df[, which(colnames(input_df) == subtype)])
  c_ij <- input_df$carriage
  d_ij <- input_df$disease
  n_i <- input_df$carriage_samples
  N_i <- input_df$surveillance_population
  t_i <- input_df$time_interval
  progression_rate_data <- list(
    i_max = max(i_values),
    j_max = max(j_values),
    n_obs = length(c_ij),
    i_values = i_values,
    j_values = j_values,
    c_ij = c_ij,
    d_ij = d_ij,
    n_i = n_i,
    N_i = N_i,
    t_i = t_i
  )
  return(progression_rate_data)
}

#' Fit a progression rate model to case-carrier data
#'
#' @param input_data List of lists generated by `process_input_data`
#' @param type_specific Boolean specifying whether progression rates vary between types
#' @param location_adjustment Boolean specifying whether progression rates vary between locations
#' @param stat_model Whether progression to disease is "poisson" (Poisson process) or "negbin" (overdispersed negative binomial distribution)
#' @param strain_as_primary_type Whether strain should be used as the primary determinant of progression rate, and the other subtype used as the secondary determinant
#' @param strain_as_secondary_type Whether strain should be used as the secondary determinant of progression rate, and the other subtype used as the primary determinant
#' @param num_chains Number of MCMCs to be run for inference
#' @param num_iter Length of MCMCs
#' @param num_cores Number of threads used to calculate MCMCs
#' @param adapt_delta_value Target average acceptance probability of MCMCs (default = 0.8)
#'
#' @return A stanfit object
#' @export
#'
#' @examples
fit_progression_rate_model<-function(input_data,
                                     type_specific = TRUE,
                                     location_adjustment = TRUE,
                                     stat_model = "poisson",
                                     strain_as_primary_type = FALSE,
                                     strain_as_secondary_type = FALSE,
                                     num_chains = 4,
                                     num_iter = 1e4,
                                     num_cores = 1,
                                     adapt_delta_value = 0.8) {
  # Validate input
  model_suffix = match.arg(stat_model, c("poisson","negbin"), several.ok = FALSE)
  if ((strain_as_primary_type | strain_as_secondary_type) & !("strain" %in% colnames(input_data))) {
    message("If strain to be used in typing, then needs to be in input data")
    quit(status = 1)
  }
  # Select model based on specifications
  model_prefix = "null"
  if (type_specific & location_adjustment) {
    model_prefix = "adjusted_type_specific"
  } else if (type_specific & !(location_adjustment)) {
    model_prefix = "type_specific"
  } else if (!(type_specific) & location_adjustment) {
    model_prefix = "adjusted_null"
  }
  model_name = paste0(model_prefix,'_',model_suffix)
  # Validate model name
  if (!(model_name %in% names(stanmodels))) {
    message(paste(model_name,"not in list of valid model names"))
    quit(status = 1)
  }
  # Sample from model
  model_output<-
    rstan::sampling(stanmodels[[model_name]],
                    data = input_data,
                    iter = num_iter,
                    cores = num_cores,
                    chains = num_chains,
                    control = list(adapt_delta = adapt_delta_value)
    )
  # Return output
  return(model_output)
}

get_mean<-function(parameter,model) {
  return(summary(model,pars=c(parameter))$summary[,1])
}

get_upper<-function(parameter,model) {
  return(summary(model,pars=c(parameter))$summary[,8])
}

get_lower<-function(parameter,model) {
  return(summary(model,pars=c(parameter))$summary[,4])
}

#' Process the model output for downstream analysis
#'
#' @param input_df Data frame used as input to model fitting
#' @param model_output Stanfit object returned by model fitting
#' @param subtype Name of column used to define subtypes
#' @param strain_as_primary_type Whether strain was used as the primary determinant of progression rate, and the other subtype used as the secondary determinant
#' @param strain_as_secondary_type Whether strain was used as the secondary determinant of progression rate, and the other subtype used as the primary determinant
#'
#' @return A data frame
#' @export
#'
#' @examples
process_progression_rate_model_output<-function(input_df,
                                                model_output,
                                                subtype = "categorisation",
                                                strain_as_primary_type = FALSE,
                                                strain_as_secondary_type = FALSE) {
  # Extract progression rate estimates and intervals
  if (!use_strain) {
    # Carriage prevalence estimates
    carriage_df <- data.frame(
      "rho" = get_mean("rho_ij",model_output),
      "rho_lower" = get_lower("rho_ij",model_output),
      "rho_upper" = get_upper("rho_ij",model_output)
    )
    # Variation by type
    nu_name = "nu"
    if ("nu_j" %in% model_output@model_pars) {
      nu_name = "nu_j"
    }
    subtype_parameters_df <- data.frame(
      "type" = levels(input_df[[subtype]]),
      "nu" = get_mean(nu_name,model_output),
      "nu_lower" = get_lower(nu_name,model_output),
      "nu_upper" = get_upper(nu_name,model_output)
    )
    # Variation by location
    scale_parameter <- 1
    if ("delta_i" %in% model_output@model_pars) {
      location_parameters <- data.frame(
        "study" = levels(input_df[["study"]]),
        "delta" = get_mean("delta_i",model_output),
        "delta_lower" = get_lower("delta_i",model_output),
        "delta_upper" = get_upper("delta_i",model_output)
      )
    } else {
      location_parameters <- data.frame(
        "study" = levels(input_df[["study"]]),
        "delta" = 1,
        "delta_lower" = 1,
        "delta_upper" = 1
      )
    }
    # Join information together
    updated_df <-
      input_df %>%
        dplyr::bind_cols(carriage_df) %>%
        dplyr::left_join(subtype_parameters_df, by = setNames("type",subtype)) %>%
        dplyr::left_join(location_parameters, by = c("study" = "study"))
  }
  # Extract predictions and intervals
  updated_df %<>%
    dplyr::mutate(carriage_prediction = rho*carriage_samples) %>%
    dplyr::mutate(carriage_prediction_lower = qbinom(0.025, carriage_samples, rho)) %>%
    dplyr::mutate(carriage_prediction_upper = qbinom(0.975, carriage_samples, rho)) %>%
    dplyr::mutate(disease_prediction = rho*nu*delta*surveillance_population*time_interval)
  # Calculate intervals for disease isolates
  if (phi_nb %in% model_output@model_pars) {
    phi = get_mean("phi_nb",model_output)
    updated_df %<>%
      dplyr::mutate(disease_prediction_lower = qnbinom(0.025, mu = disease_prediction, size = phi)) %>%
      dplyr::mutate(disease_prediction_upper = qnbinom(0.975, mu = disease_prediction, size = phi))
  } else {
    updated_df %<>%
      dplyr::mutate(disease_prediction_lower = qpois(0.025, disease_prediction)) %>%
      dplyr::mutate(disease_prediction_upper = qpois(0.975, disease_prediction))
  }
  return(updated_df)
}


